image:
  repository: nextcloud
  flavor: fpm  # Using fpm instead of apache
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  path: /
  pathType: Prefix

nginx:
  enabled: true  # This enables nginx
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  config:
    # This generates the default nginx config as per nextcloud documentation
    default: true
    # Additional security headers
    headers:
      "Strict-Transport-Security": "max-age=15768000"
      "Referrer-Policy": "no-referrer"
      "X-Content-Type-Options": "nosniff"
      "X-Download-Options": "noopen"
      "X-Frame-Options": "SAMEORIGIN"
      "X-Permitted-Cross-Domain-Policies": "none"
      "X-Robots-Tag": "noindex, nofollow"
      "X-XSS-Protection": "1; mode=block"

nextcloud:
  host: "your-domain.com"  # Replace with your domain
  username: "patrick"
  password: "STRONG-PASSWORD-HERE"  # Replace with strong password
  
  # PHP Configuration for better performance
  phpConfigs:
    custom.ini: |-
      memory_limit=512M
      upload_max_filesize=1024M
      post_max_size=1024M
      max_execution_time=300
      max_input_time=300

# Disable internal database since we're using MariaDB
internalDatabase:
  enabled: false

# Enable MariaDB
mariadb:
  enabled: true
  auth:
    database: nextcloud
    username: nextcloud
    password: "STRONG-MARIADB-PASSWORD"  # Replace with strong password
    rootPassword: "STRONG-ROOT-PASSWORD"  # Replace with strong password
  primary:
    persistence:
      enabled: true
      storageClass: "local-path"  # K3s default storage class
      size: 10Gi

# Enable Redis for better performance
redis:
  enabled: true
  auth:
    password: "STRONG-REDIS-PASSWORD"  # Replace with strong password
  master:
    persistence:
      enabled: true
      size: 5Gi

# Main Nextcloud storage
persistence:
  enabled: true
  storageClass: "local-path"  # K3s default storage class
  size: 30Gi
  
  # Separate data directory on different volume
  nextcloudData:
    enabled: true
    storageClass: "local-path"
    size: 100Gi

# Resource limits
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 2000m
    memory: 2Gi

# Enable HTTPS redirect
phpClientHttpsFix:
  enabled: true
  protocol: https

# Enable periodic background jobs
cronjob:
  enabled: true

# Pod security context
podSecurityContext:
  runAsUser: 33
  runAsGroup: 33
  fsGroup: 33

# Probes configuration for better stability
startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30
  successThreshold: 1

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
